name: VirusTotal Full Scan

on:
  push:
    branches: [ main ]
  pull_request:  # Опционально: проверка и при PR

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find all files and scan with VirusTotal
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ${{ steps.find_files.outputs.files }}
        env:
          VT_DEBUG: 1  # Детальный лог (опционально)
        id: scan_files

      - name: List files to scan
        run: |
          echo "Files to scan:"
          echo "${{ steps.find_files.outputs.files }}"
