name: VirusTotal Scan on Push
on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Клонирует репозиторий

      - name: Scan file with VirusTotal
        uses: filips123/VirusTotal-Action@v1
        with:
          api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
          file_path: ./bin/app.exe  # Путь к файлу в репозитории
          public_share: true